version: '3.8'

services:
  postgres-container:
    image: postgres
    container_name: pg-unity-test
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
